welcome-message: False
web:
  webhook-token: "S00p3r3cureToken"
#  base-url: https://f7b4-91-107-239-247.ngrok-free.app


connectors:
  matrix:
    # Required
    mxid: "@bot_dev_reg:parsi.ai"
    password: "123456"
    rooms:
      'main': '#memyselfandsaee:parsi.ai'
    # Optional
    homeserver: "https://parsi.ai"
    nick: "testorooni"  # The nick will be set on startup
    device_id: "OPSDroid"
    enable_encryption: True

#  telegram:
#    # required
#    token: "6075160316:AAHsYGo1pewwSZQMgkC-XZQCOs7onMHGep4"  # Telegram bot token
#    # optional
#    bot-name: opsdroid # Name to be used by the bot in some replies, defaults to opsdroid
#    reply-unauthorized: True # Should the bot reply to unauthorized users?


skills:
  hello: { }
  buttons:
    path: custom_skills/webhooks.py
  ping:
    path: custom_skills/ping_skill.py
  tooti:
    path: custom_skills/tooti_skill.py
  image_not_recognizer:
    path: custom_skills/image_not_recognizer.py

logging:
  level: info
  path: ~/.opsdroid/output.log
  console: true
  extended: true