connectors:
  matrix:
    # Required
    mxid: "@bot_dev_reg:parsi.ai"
    password: "123456"
    rooms:
      'main': '#memyselfandsaee:parsi.ai'
    # Optional
    homeserver: "https://parsi.ai"
    nick: "testorooni"  # The nick will be set on startup
    device_id: "OPSDroid"
    enable_encryption: True


skills:
  ping:
    path: custom_skills/ping_skill.py